version: "3.8"
# FILEPATH: /home/germain/Documents/Projets/recipe-app/compose.yml

# Docker Compose file for a recipe app

services:
   # Frontend service
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
      - db
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://localhost:3001
      - BACKEND_PORT=3001

   # Backend service
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@localhost:5432
    depends_on:
      - db
    restart:
      always
    ports:
      - "3001:3001"
    networks:
        - backend-network

# Database service
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    networks:
        - backend-network
volumes :
  data:
networks:
    backend-network:
        driver: bridge