version: "3.8"
services:
  front:
    build:
      context: front
      dockerfile: Dockerfile
    depends_on:
      - back
    ports:
      - "3000:3000"
    environment:
      - API_PORT = 3001
      - PORT = 3000
  back:
    build:
        context: backend
        dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3001:3001"
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d data"]
      interval: 10s
      timeout: 5s
      retries: 3

