version: "3.8"
# FILEPATH: /home/germain/Documents/Projets/recipe-app/compose.yml

# Docker Compose file for a recipe app

services:
#   # Frontend service
#   front:
#     build:
#       context: front
#       dockerfile: Dockerfile
#     depends_on:
#       - back
#     ports:
#       - "3000:3000"
#     environment:
#       - API_PORT=3001
#       - PORT=3000

#   # Backend service
#   back:
#     build:
#       context: backend
#       dockerfile: Dockerfile
#     depends_on:
#       - db
#     ports:
#       - "3001:3001"

#   db:
#     image: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - ./data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres -d data"]
#       interval: 10s
#       timeout: 5s
#       retries: 3
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
volumes :
  data:
