version: "3.8"
# FILEPATH: /home/germain/Documents/Projets/recipe-app/compose.yml

# Docker Compose file for a recipe app

services:
   # Frontend service
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://localhost:3001
      - BACKEND_PORT=3001

   # Backend service
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres.tftrtynikqeammzejksj:kROxUtfZii7GRBh7@aws-0-eu-central-1.pooler.supabase.com:5432/postgres
      - DB_PASSWORD=kROxUtfZii7GRBh7
      - API_KEY=f7b9d099954a4955a153f2d62f2b49e2
    restart:
      always
    ports:
      - "3001:3001"


