version: "3.8"
services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
    environment:
      - API_PORT = 3001
      - PORT = 3000
  api:
    build:
        context: backend
        dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_URL = postgres://fl0user:FxUDTnLt4EC3@ep-gentle-snowflake-a287b2br.eu-central-1.aws.neon.fl0.io:5432/recipe-db?sslmode=require
      - DB_USER = fl0user
      - DB_PASSWORD = FxUDTnLt4EC3
      - DB_HOST = ep-gentle-snowflake-a287b2br.eu-central-1.aws.neon.fl0.io
      - DB_PORT = 5432
      - PORT = 3001
      - DB_NAME = recipe-db


