version: "3.8"
services:
  web:
    build:
      context: frontend
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
  api:
    build:
        context: backend
        dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "3001:3001"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment: 
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes: 
      - postgres:/var/lib/postgresql/data
volumes:
    postgres:
        driver: local
